---
name: Check and get changes since last Deployment
description: hello
inputs:
  project-alias:
    description: the project alias for the project you are running a deployment on
    required: true
  api-key:
    description: key needed to have access to api
    required: true
  workspace:
    description: github workspace
    required: true
  github-pat-token:
    description: github token to be able to apply git patch to a branch
    required: true
  pipeline-run:
    description: the name of the current run or version
    required: true
outputs:
  REMOTE_CHANGES:
    description: set to true if cloud repo is ahead of latest deployment id
  PATCH_FILE:
    description: location of patch file

runs:
  using: node16
  main: action/index.js